package com.automation.agents;

import com.automation.models.JiraTicket;
import com.automation.models.TestCase;
import com.automation.models.XPathElement;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * ScriptGeneratorAgent — converts TestCase objects into ready-to-run
 * Cucumber feature files AND generates the matching Java step definitions.
 *
 * Output paths:
 *   Feature files  → src/test/resources/features/<pageName>/<ticketKey>.feature
 *   Step defs      → src/test/java/com/automation/steps/<pageName>Steps.java
 *   Page objects   → src/test/java/com/automation/pages/<pageName>Page.java
 */
public class ScriptGeneratorAgent extends BaseAgent {

    private static final Logger log = LogManager.getLogger(ScriptGeneratorAgent.class);
    private static final String FEATURES_BASE = "src/test/resources/features";
    private static final String STEPS_BASE = "src/test/java/com/automation/steps";
    private static final String PAGES_BASE = "src/test/java/com/automation/pages";

    // ── Feature File Generation ────────────────────────────────────────────────

    /**
     * Generate a .feature file from a list of test cases for a given ticket.
     */
    public Path generateFeatureFile(JiraTicket ticket, List<TestCase> testCases) {
        log.info("Generating feature file for ticket: {}", ticket.getKey());

        StringBuilder feature = new StringBuilder();
        feature.append("@").append(ticket.getKey().toLowerCase().replace("-", "")).append("\n");
        feature.append("Feature: ").append(ticket.getSummary()).append("\n");
        feature.append("  # Jira: ").append(ticket.getKey())
               .append(" | Type: ").append(ticket.getIssueType())
               .append(" | Priority: ").append(ticket.getPriority()).append("\n");
        feature.append("  # Auto-generated by ScriptGeneratorAgent\n\n");

        if (ticket.getDescription() != null && !ticket.getDescription().isEmpty()) {
            feature.append("  Background information:\n");
            wrapText(ticket.getDescription(), 80).forEach(line ->
                feature.append("  # ").append(line).append("\n"));
            feature.append("\n");
        }

        testCases.forEach(tc -> {
            feature.append(tc.toBddScenario());
            feature.append("\n");
        });

        String pageName = derivePageName(ticket);
        Path featurePath = Paths.get(FEATURES_BASE, pageName, ticket.getKey() + ".feature");

        try {
            Files.createDirectories(featurePath.getParent());
            Files.writeString(featurePath, feature.toString(), StandardCharsets.UTF_8);
            log.info("Feature file written: {}", featurePath);
        } catch (IOException e) {
            log.error("Failed to write feature file: {}", e.getMessage());
        }

        return featurePath;
    }

    /**
     * Use AI to generate Java step definitions for the given test cases.
     */
    public Path generateStepDefinitions(JiraTicket ticket, List<TestCase> testCases,
                                        List<XPathElement> elements) {
        log.info("Generating step definitions for: {}", ticket.getKey());

        String pageName = derivePageName(ticket);
        String className = capitalize(pageName) + "Steps";
        String pageClassName = capitalize(pageName) + "Page";

        String elementRegistry = elements.stream()
            .map(e -> "  " + e.getKey() + " -> " + e.getBestLocator() + " (" + e.getDescription() + ")")
            .collect(Collectors.joining("\n"));

        String stepsList = testCases.stream()
            .flatMap(tc -> tc.getSteps().stream())
            .map(s -> s.getAction() + " " + s.getDescription())
            .distinct()
            .collect(Collectors.joining("\n"));

        String systemPrompt = """
            You are a Java Cucumber automation engineer.
            Generate a complete Java step definitions class using:
            - Cucumber 7 annotations (@Given, @When, @Then, @And)
            - Page Object Model pattern
            - Clear method names that match the Gherkin steps
            - Logger calls for each step
            - Assertions using TestNG Assert
            - PicoContainer for dependency injection

            Return ONLY valid Java code. No markdown fences.
            Use package com.automation.steps;
            """;

        String userPrompt = String.format("""
            Generate step definitions class "%s" for page "%s".

            Available XPath Registry elements:
            %s

            Gherkin steps to implement:
            %s

            The page class is: com.automation.pages.%s
            Include constructor with %s parameter for dependency injection.
            """, className, pageName, elementRegistry, stepsList, pageClassName, pageClassName);

        String javaCode = askClaude(systemPrompt, userPrompt, 6144);

        // Fallback if AI response is empty
        if (javaCode.startsWith("[MOCK]") || javaCode.startsWith("ERROR:")) {
            javaCode = generateFallbackSteps(className, pageClassName, testCases);
        }

        Path stepsPath = Paths.get(STEPS_BASE, className + ".java");
        try {
            Files.createDirectories(stepsPath.getParent());
            Files.writeString(stepsPath, javaCode, StandardCharsets.UTF_8);
            log.info("Step definitions written: {}", stepsPath);
        } catch (IOException e) {
            log.error("Failed to write step definitions: {}", e.getMessage());
        }

        return stepsPath;
    }

    /**
     * AI-generated Page Object for the given page.
     */
    public Path generatePageObject(String pageName, List<XPathElement> elements) {
        log.info("Generating page object for: {}", pageName);

        String className = capitalize(pageName) + "Page";

        String elementsDescription = elements.stream()
            .map(e -> String.format("  %-40s | %-10s | %s",
                e.getKey(), e.getElementType(), e.getBestLocator()))
            .collect(Collectors.joining("\n"));

        String systemPrompt = """
            You are a Java Selenium automation engineer.
            Generate a complete Page Object Model class with:
            - @FindBy annotations for all provided elements
            - PageFactory.initElements in constructor
            - Action methods that wrap WebElement interactions
            - WaitUtils for reliable waits
            - Clear Javadoc on each public method
            - Logger for each action

            Return ONLY valid Java code. No markdown fences.
            Use package com.automation.pages;
            """;

        String userPrompt = String.format("""
            Generate page object class "%s" for page "%s".
            Base URL context: %s

            Elements to model:
            %s

            Extend BasePage. Constructor takes WebDriver parameter.
            """, className, pageName, config.getBaseUrl(), elementsDescription);

        String javaCode = askClaude(systemPrompt, userPrompt, 6144);

        if (javaCode.startsWith("[MOCK]") || javaCode.startsWith("ERROR:")) {
            javaCode = generateFallbackPage(className, pageName, elements);
        }

        Path pagePath = Paths.get(PAGES_BASE, className + ".java");
        try {
            Files.createDirectories(pagePath.getParent());
            Files.writeString(pagePath, javaCode, StandardCharsets.UTF_8);
            log.info("Page object written: {}", pagePath);
        } catch (IOException e) {
            log.error("Failed to write page object: {}", e.getMessage());
        }

        return pagePath;
    }

    /**
     * Full pipeline: Jira ticket → test cases → feature file + steps + page object.
     */
    public GenerationResult generateAll(JiraTicket ticket, List<TestCase> testCases,
                                        List<XPathElement> elements) {
        Path featurePath = generateFeatureFile(ticket, testCases);
        Path stepsPath   = generateStepDefinitions(ticket, testCases, elements);
        String pageName  = derivePageName(ticket);
        Path pagePath    = generatePageObject(pageName, elements);

        return new GenerationResult(featurePath, stepsPath, pagePath, testCases.size());
    }

    // ── Fallback generators (no AI key) ───────────────────────────────────────

    private String generateFallbackSteps(String className, String pageClassName,
                                         List<TestCase> testCases) {
        StringBuilder sb = new StringBuilder();
        sb.append("package com.automation.steps;\n\n");
        sb.append("import com.automation.pages.").append(pageClassName).append(";\n");
        sb.append("import io.cucumber.java.en.*;\n");
        sb.append("import org.apache.logging.log4j.*;\n\n");
        sb.append("public class ").append(className).append(" {\n\n");
        sb.append("    private static final Logger log = LogManager.getLogger(")
          .append(className).append(".class);\n");
        sb.append("    private final ").append(pageClassName).append(" page;\n\n");
        sb.append("    public ").append(className).append("(")
          .append(pageClassName).append(" page) { this.page = page; }\n\n");

        testCases.stream().flatMap(tc -> tc.getSteps().stream()).distinct().forEach(step -> {
            String methodName = step.getDescription()
                .replaceAll("[^a-zA-Z0-9 ]", "").trim()
                .replaceAll("\\s+", " ")
                .replace(" ", "_").toLowerCase();
            if (methodName.length() > 50) methodName = methodName.substring(0, 50);

            String annotation = switch (step.getAction()) {
                case "Given" -> "@Given";
                case "When"  -> "@When";
                case "Then"  -> "@Then";
                default      -> "@And";
            };

            sb.append("    ").append(annotation)
              .append("(\"").append(step.getDescription().replace("\"", "'")).append("\")\n");
            sb.append("    public void ").append(methodName).append("() {\n");
            sb.append("        log.info(\"Step: ").append(step.getDescription().replace("\"", "'")).append("\");\n");
            sb.append("        // TODO: implement using page.xxx()\n");
            sb.append("    }\n\n");
        });

        sb.append("}\n");
        return sb.toString();
    }

    private String generateFallbackPage(String className, String pageName,
                                        List<XPathElement> elements) {
        StringBuilder sb = new StringBuilder();
        sb.append("package com.automation.pages;\n\n");
        sb.append("import com.automation.core.BasePage;\n");
        sb.append("import org.openqa.selenium.*;\n");
        sb.append("import org.openqa.selenium.support.*;\n\n");
        sb.append("public class ").append(className).append(" extends BasePage {\n\n");

        elements.forEach(el -> {
            String loc = el.getId() != null && !el.getId().isEmpty()
                ? "@FindBy(id = \"" + el.getId() + "\")"
                : "@FindBy(xpath = \"" + el.getXpath() + "\")";
            sb.append("    ").append(loc).append("\n");
            sb.append("    private WebElement ").append(toCamelCase(el.getKey())).append(";\n\n");
        });

        sb.append("    public ").append(className).append("(WebDriver driver) {\n");
        sb.append("        super(driver);\n");
        sb.append("        PageFactory.initElements(driver, this);\n");
        sb.append("    }\n\n");

        elements.stream()
            .filter(e -> e.getElementType() != null && e.getElementType().equals("INPUT"))
            .forEach(el -> {
                String fieldName = toCamelCase(el.getKey());
                String methodName = "enter" + capitalize(fieldName.replace("Input", "").replace("Field", ""));
                sb.append("    public void ").append(methodName).append("(String value) {\n");
                sb.append("        clearAndType(").append(fieldName).append(", value);\n");
                sb.append("    }\n\n");
            });

        elements.stream()
            .filter(e -> e.getElementType() != null && e.getElementType().equals("BUTTON"))
            .forEach(el -> {
                String fieldName = toCamelCase(el.getKey());
                String methodName = "click" + capitalize(fieldName.replace("Button", "").replace("Btn", ""));
                sb.append("    public void ").append(methodName).append("() {\n");
                sb.append("        click(").append(fieldName).append(");\n");
                sb.append("    }\n\n");
            });

        sb.append("}\n");
        return sb.toString();
    }

    // ── Utilities ──────────────────────────────────────────────────────────────

    private String derivePageName(JiraTicket ticket) {
        if (ticket.getLabels() != null && !ticket.getLabels().isEmpty()) {
            return ticket.getLabels().get(0).toLowerCase();
        }
        return ticket.getKey().split("-")[0].toLowerCase();
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private String toCamelCase(String upperSnake) {
        String[] parts = upperSnake.toLowerCase().split("_");
        StringBuilder sb = new StringBuilder(parts[0]);
        for (int i = 1; i < parts.length; i++) {
            sb.append(capitalize(parts[i]));
        }
        return sb.toString();
    }

    private List<String> wrapText(String text, int width) {
        List<String> lines = new java.util.ArrayList<>();
        String[] words = text.split("\\s+");
        StringBuilder line = new StringBuilder();
        for (String word : words) {
            if (line.length() + word.length() + 1 > width) {
                lines.add(line.toString());
                line = new StringBuilder();
            }
            if (!line.isEmpty()) line.append(" ");
            line.append(word);
        }
        if (!line.isEmpty()) lines.add(line.toString());
        return lines;
    }

    // ── Result DTO ─────────────────────────────────────────────────────────────

    public record GenerationResult(Path featurePath, Path stepsPath, Path pagePath, int testCaseCount) {
        @Override
        public String toString() {
            return String.format("Generated %d test cases → Feature: %s | Steps: %s | Page: %s",
                testCaseCount, featurePath, stepsPath, pagePath);
        }
    }
}
